### ISSUE TITLE
Please complete the wiki documentation: On how to add library to the exisiting project

### ISSUE THREAD

**Issue by ansari-haseb** [kalemontes/OIDCAndroidLib#14]

**Comment by kalemontes** [comment]
Hi Ansari,

Am not maintaining this librarie anymore.This project has been dead for a year or so.

This librairie had some sense when i started this implémentation since there was no standard or guidelines on how to do what it did.

But since the release of the RFC https://tools.ietf.org/html/rfc8252 (released on october 2017) there are a series of best practices and security considerations that this librarie just does not follow.

So i encourage you to take a look on some other libraries that follow that RFC, for instance https://github.com/openid/AppAuth-Android (i've been looking to this on myself as a candidate to replace my own usages).

Hope this helps you.
