### ISSUE TITLE
Launching intent when refresh token expired doesn't work

### ISSUE THREAD

**Issue by menloperk** [kalemontes/OIDCAndroidLib#4]
I have implemented your oidcsample in Android Studio and was able to get it working quite easily. For testing I have set my access token to expire after 1 minute and my refresh token after 2 minutes. Logging in gives no issue. Waiting somewhat more than 1 minute and then clicking on the 'LOGGED IN AS RENE.KLOMP' button nicely refreshes the tokens:

`D/AuthenticatorService: Binding Authenticator.`
`D/Authenticator: Authenticator created.`
`D/Authenticator: getAuthToken called with account.type 'com.demolab.oidclib.account', account.name 'RENE.KLOMP (8:669rRyPpLYw7fgPd2EQ0JDIIHU0ApbH4F2LOzFTnSxw)', authTokenType 'com.lnikkila.oidcsample.TOKEN_TYPE_ACCESS'.`
`D/Authenticator: Token empty, checking for refresh token.`
`D/Authenticator: Got refresh token, getting new tokens.`
`D/Authenticator: The OIDC client options are correctly set.`
`D/Authenticator: Got new tokens.`
`D/Authenticator: Returning token 'eyJ0e.....aA0Hs' of type 'com.lnikkila.oidcsample.TOKEN_TYPE_ACCESS'.`
`I/HomeActivity: We manage to login user to server`

However, when I wait longer than 2 minutes (so the refresh token has expired), it claims 'launching intent for renewing authorisation' but instead of seeing a new login screen it throws an exception (401 Unauthorized):

`D/AuthenticatorService: Binding Authenticator.`
`D/Authenticator: Authenticator created.`
`D/Authenticator: getAuthToken called with account.type 'com.demolab.oidclib.account', account.name 'RENE.KLOMP (8:669rRyPpLYw7fgPd2EQ0JDIIHU0ApbH4F2LOzFTnSxw)', authTokenType 'com.lnikkila.oidcsample.TOKEN_TYPE_ACCESS'.`
`D/Authenticator: Token empty, checking for refresh token.`
`D/Authenticator: Got refresh token, getting new tokens.`
`D/Authenticator: The OIDC client options are correctly set.`
`D/Authenticator: Refresh token expired response detected`
`D/Authenticator: Refresh token expired, launching intent for renewing authorisation.`
`W/System.err: java.io.IOException: 401 Unauthorized`
`W/System.err:     at com.lnikkila.oidcsample.APIUtility.makeRequest(APIUtility.java:89)`
`W/System.err:     at com.lnikkila.oidcsample.APIUtility.makeRequest(APIUtility.java:86)`
`W/System.err:     at com.lnikkila.oidcsample.APIUtility.makeRequest(APIUtility.java:51)`
`W/System.err:     at com.lnikkila.oidcsample.APIUtility.getJson(APIUtility.java:37)`
`W/System.err:     at com.lnikkila.oidcsample.HomeActivity$LoginTask.doInBackground(HomeActivity.java:191)`
`W/System.err:     at com.lnikkila.oidcsample.HomeActivity$LoginTask.doInBackground(HomeActivity.java:174)`
`W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)`
`W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)`
`W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)`
`W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)`
`W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)`
`W/System.err:     at java.lang.Thread.run(Thread.java:818)`
`W/HomeActivity: We couldn't fetch userinfo from server`

In the yellow button the obviously appears 'COULDN'T GET USER INFO'.
What could be going on here?!

Thanks, Rene.

**Comment by kalemontes** [comment]
Well this is normal since is the AccountManager has to tell the user that he needs to authenticate again. Don't you have a notification on the status bar telling you that the AccountManager needs your attention ? If you don't it is a bug, if you do, click on the notification and the AuthenticatorActivity should pop asking the user for his credentials.

I don't have a context in which i can test this now but i'll be happy to give you support if you still need it.

**Comment by kalemontes** [comment]
If you want to handle the user re-authentication event inside your application i belive you have to register an AccountManagerCallback when calling [APIUtility.getJson()](https://github.com/kalemontes/OIDCAndroidLib/blob/master/oidclib-sample/src/main/java/com/lnikkila/oidcsample/APIUtility.java) so it'll request tokens to the [AccountManager](http://goo.gl/R7v67q) using the given callback. 

Finally, you have to detect the `"good"` callback event, extract the intent and start an activity using that intent. I haven't test this but it should work.

Here is an example of how to do it http://stackoverflow.com/a/26911824/665823

**Comment by menloperk** [comment]
I guess it was me not fully understanding the use case as it relates to 
the UI.
Indeed, I get a notification (triangle with exclamation mark) with 
something saying 'Signin error...' or similar.
If I click on it, I am able to re-authenticate.

I was just expecting this to happen more automatically, I suppose...

Cheers, Rene.

**Comment by menloperk** [comment]
Yes, that's what I was looking for. I will try to give it a go...

Thanks, Rene.

**Comment by kalemontes** [comment]
This is a litle late but for completeness sake here is reason why a notification pops instead of just show you the authentication webview.

Consider the following scenario ( on an office paradigm  ) : 
- You have an android service that syncs data on background. He is an intern (because they are the ones doing the hard and annoying work, right?)
- It uses the AT store on the AccountManager to make it's request to the SP. In the office paradigm it means that every day\* he asks the badge of his office to the security guard. 
- So he has been happily been doing his job since he started working.
- One day his AT expire, so when requesting data from the SP gets `401 Unauthorized`. Again in the office paradigm he uses his badge to access the office but can't get in.
- When this happends your service has to _tell_ the AccountManager (intern goes back talk to the security guard) :
  
  > Dude, the badge you gave me ain't working no more, can you fetch me another one pretty please! 
- So the AccountManager invalidates the AT then tries to refresh it using the RT (the security guard destroys the badge and goes fetch another)
- Your service is out of luck, your RT also expire just 3 seconds ago. So the AccountManager will _answer_ to your service 
  
  > Sorry dude, i couldn't get you the badge you need because the OP (the badge delivery guy) told me that the end user (the big boss) needs to authenticate it's self again (the big boss authorization). 
  > 
  >  I don't want to disturb him myself because he might be busy. I left him a message with his sexy secretary (the Android notification system) but if you really need it now you should ask the end user to authenticate. Here is his personal phone number (the returned intent).
- So the AccountManager just poped a notification telling the end user that he requires some attention in order to continue delivering badges
- Your service being a intern, should not dare to disturb the big boss. So he'll patiently wait until the end user re authenticates to continue doing his work. So he tells to himself :
  
  > Well i'll ask the AccountManager tomorrow if he managed to get a new AT
- It could be imediatly or it could take ages (bosses are bosses and they do what they got to do on their own time) for the end user to authenticate.

The moral of this little story is that services should never just pop and interrupt the end user with requests. And this is why you don't see the AuthenticationActivity poping right up when the refresh token expires.

Now consider the next scenario ( we still in an office paradigm and it will look a lot as the previous but is not the same ) :
- You have an android app that is being use by the end user. So your app is an important business partner and has a meeting with the big boss
- It also uses the AT store on the AccountManager to make it's request to the SP. In the office paradigm it means that he asks the security guard for a badge when getting to the meeting office.
- Usually this badge works and your app has access to the SP data (so the business partner can get directly in the meeting office and do it's work)
- On day your app gets from your SP a `401 Unauthorized`. Again in the office paradigm he uses his badge to access the office but can't get in.
- When this happends your app has to _tell_ the AccountManager (business partner goes back talk to the security guard) :
  
  > Excuse me, the badge you gave me today is not working and i have a meeting with the boss
- So the AccountManager invalidates the AT then tries to refresh it using the RT (the security guard destroys the badge and goes fetch another)
- Your app is out of luck, your RT also expire just 3 seconds ago. So the AccountManager will _answer_ to your app
  
  > Sorry Mr. Business partner, i couldn't get you the badge you need because the OP (the badge delivery guy) told me that the end user (the big boss) needs to authenticate it's self again (the big boss authorization).
  > 
  > I don't want to disturb him myself because he might be busy. I left him a message with his sexy secretary (the Android notification system) but if you really need it now you should ask the end user to authenticate. Here is his personal phone number (the returned intent).
- So this time since the end user is interacting with your app and that he needs to access the data on the SP right now. Your app can interrupt the end user to tell him that his authorization is required to continue. It will use the intent that the AccountManager gave it to do this. But in order to known when to return to it's normal work, it has to know when the new tokens are delievered. This is were the callback event is needed.
- To finish the office paradigm scenario (because all stories should have an end), the business partner calls the boss, tells him that he has no access to the meeting office. The boss calls the badge delivery guy to tell him to make a new bad. When done the security guard goes get them and gives them to the business partner. And finally the business partner can get to the office and start the meating with the big boss.

So the moral of both stories is that interns always get screw...No actually, to be more serious, is that the AccountManager gives us a way  to handle both cases.

Hope you enjoy my stories.

**Comment by kalemontes** [comment]
Well i added a way to handle user re-authentication event inside the app. Check the sample project on : https://github.com/kalemontes/OIDCAndroidLib/commit/e2cfd2f6125f9d7aee89661e74429c143cfbaa53
