### ISSUE TITLE
Clarify procedure for logging out

### ISSUE THREAD

**Issue by nckackerman** [kalemontes/OIDCAndroidLib#5]
Thanks for your hard work! We've been able to successfully log users in using our keycloak server with your library.

However, I am unclear how to properly logout a user. Can you offer some clarification on this and consider putting such clarification into the documentation?

**Comment by kalemontes** [comment]
Hi @nckackerman, thanks for the feedback.

This is a tricky question because it depends on what you are calling _loggin out_. You have to consider both client and server sides needs. You are right, i should try to explain this somewhere.

**Let's start with a general explanation :**

In a RP point of view, loggin out can be translated as clearing the tokens you got from the OP. If your RP, here the android OIDC client app, doesn't have tokens then it can't request data from your SP, am i right ? But this does not mean that thoses tokens are invalid to the OP. Actually if another RP uses thoses same tokens it can continue to request data from your SP. This is were the revocation endpoint pops in.

So to make server logout, your RP has to tell the OP that the user doesn't want that thoses tokens that he has gotten, to continue to be use by him or any other client. This is usually done by making an REST request to the revocation endpoint with the token you want to revoke https://tools.ietf.org/html/rfc7009

But even when you have done that, it still doesn't mean that the user session has ended. Other tokens for the same user could have been delivered to other RP (or the same in other device for instance).

 Read more about this on http://openid.net/specs/openid-connect-session-1_0.html#RPLogout

**Now let's go back to the lib :**

If you just need to clear the tokens from the RP, you should call [OIDCAccountManager.removeAccount(String accountName)](https://github.com/kalemontes/OIDCAndroidLib/blob/master/oidclib/src/main/java/com/lnikkila/oidc/OIDCAccountManager.java) to clear them. As you have guess this removes the account created to store the tokens from the AccountManager.

In the other hand if you want to revoke the tokens from the OP, you need to make a HTTP request and as for now i don't have a "standard" way of doing this. The OP i use, uses some specifics to revoke user tokens. I'll try to focus in this sometime soon. Any pull request on this will be apreciated.

Hope this makes the logout precedure more clear.

**Comment by kalemontes** [comment]
Well i added a sample on how you could do this to the sample project https://github.com/kalemontes/OIDCAndroidLib/commit/482cb38285fe53636cb086941e4ee6ee1c5aec91 . The server side revocation is not implemented though.
